---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: libvirt
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.openstack.libvirt
      dest:
        path: .source
    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.osh.libvirt
      dest:
        path: .values.images.tags
data:
  chart_name: libvirt
  release: openstack-libvirt
  namespace: openstack
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    labels:
      agent:
        libvirt:
          node_selector_key: openstack-compute-node
          node_selector_value: enabled
    network:
      backend:
        - tungstenfabric
    dependencies:
      dynamic:
        targeted:
          tungstenfabric:
            libvirt:
              daemonset: []
    conf:
      ceph:
        enabled: false
      qemu:
        cgroup_device_acl: ["/dev/null", "/dev/full", "/dev/zero", "/dev/random", "/dev/urandom", "/dev/ptmx", "/dev/kvm", "/dev/kqemu", "/dev/rtc", "/dev/hpet", "/dev/net/tun"]
  dependencies:
    - openstack-libvirt-helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: openstack-libvirt-helm-toolkit
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.openstack.libvirt-htk
      dest:
        path: .source
data:
  chart_name: openstack-libvirt-helm-toolkit
  release: openstack-libvirt-helm-toolkit
  namespace: helm-toolkit
  values: {}
  dependencies: []
