---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: neutron
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.openstack.neutron
      dest:
        path: .source
    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.osh.neutron
      dest:
        path: .values.images.tags
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .tungstenfabric.ip
      dest:
        path: .values.conf.plugins.tungstenfabric.APISERVER.api_server_ip
data:
  chart_name: neutron
  release: neutron
  namespace: openstack
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            application: neutron
            component: db-init
        - type: job
          labels:
            application: neutron
            component: db-sync
        - type: job
          labels:
            application: neutron
            component: ks-user
        - type: job
          labels:
            application: neutron
            component: ks-service
        - type: job
          labels:
            application: neutron
            component: ks-endpoints
  wait:
    timeout: 1800
  values:
    images:
      tags:
        opencontrail_neutron_init: opencontrailnightly/contrail-openstack-neutron-init:ocata-master-latest
    labels:
      agent:
        dhcp:
          node_selector_key: openstack-control-plane
          node_selector_value: enabled
        l3:
          node_selector_key: openstack-control-plane
          node_selector_value: enabled
        metadata:
          node_selector_key: openstack-control-plane
          node_selector_value: enabled
      job:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      lb:
        node_selector_key: linuxbridge
        node_selector_value: enabled
      ovs:
        node_selector_key: openvswitch
        node_selector_value: enabled
      server:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      test:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
    network:
      backend:
        - tungstenfabric
    dependencies:
      dynamic:
        targeted:
          tungstenfabric:
            server:
              daemonset: []
    conf:
      openstack_version: ocata
      neutron:
        DEFAULT:
          core_plugin: neutron_plugin_contrail.plugins.opencontrail.contrail_plugin.NeutronPluginContrailCoreV2
          service_plugins: neutron_plugin_contrail.plugins.opencontrail.loadbalancer.v2.plugin.LoadBalancerPluginV2
          l3_ha: False
          max_l3_agents_per_router: 1
          l3_ha_network_type: vxlan
          dhcp_agents_per_network: 1
          api_extensions_path: /opt/plugin/site-packages/neutron_plugin_contrail/extensions:/opt/plugin/site-packages/neutron_lbaas/extensions
          interface_driver: null
        quotas:
          quota_driver: neutron_plugin_contrail.plugins.opencontrail.quota.driver.QuotaDriver
      plugins:
        tungstenfabric:
          APISERVER:
            api_server_ip: config-api-server.tf.svc.cluster.local
            api_server_port: 8082
            contrail_extensions: "ipam:neutron_plugin_contrail.plugins.opencontrail.contrail_plugin_ipam.NeutronPluginContrailIpam,policy:neutron_plugin_contrail.plugins.opencontrail.contrail_plugin_policy.NeutronPluginContrailPolicy,route-table:neutron_plugin_contrail.plugins.opencontrail.contrail_plugin_vpc.NeutronPluginContrailVpc,contrail:None,service-interface:None,vf-binding:None"
            multi_tenancy: True
          KEYSTONE:
            insecure: True
    manifests:
      daemonset_dhcp_agent: false
      daemonset_l3_agent: false
      daemonset_lb_agent: false
      daemonset_metadata_agent: false
      daemonset_ovs_agent: false
      daemonset_sriov_agent: false
      pod_rally_test: false
  dependencies:
    - openstack-neutron-helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: openstack-neutron-helm-toolkit
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.openstack.neutron-htk
      dest:
        path: .source
data:
  chart_name: openstack-neutron-helm-toolkit
  release: openstack-neutron-helm-toolkit
  namespace: helm-toolkit
  values: {}
  dependencies: []
