---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-maas
  replacement: true
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: ucp-maas
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: deckhand/CertificateKey/v1
        name: airship_drydock_kvm_ssh_key
        path: .
      dest:
        path: .values.conf.ssh.private_key
data:
  values:
    manifests:
      secret_ssh_key: true
    conf:
      maas:
        dns: {dns_servers: '172.24.1.9'}
        ntp: {use_external_only: 'true' }
      cache: {enabled: true}
    network:
      maas_ingress:
        addr: '172.24.1.5/32'
...
