---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: contrail-controller
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  description: "Contrail Controller components"
  sequenced: False
  chart_group:
    - controller
    - analytics
    - thirdparty
