---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ingress-kube-system
  replacement: true
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
        name: ingress-kube-system
    actions:
        - method: merge
          path: .
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: dev/Configurables/v1
        name: dev-configurables
        path: .hostcidr
      dest:
        path: .values.network.vip.addr
        pattern: REPLACEME
data:
  values:
    network:
      ingress:
        disable-ipv6: "true"
      vip:
        manage: true
        addr: REPLACEME
...
