---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: analytics
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.tungstenfabric.analytics
      dest:
        path: .source
    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.tungstenfabric.analytics
      dest:
        path: .values.global.images.tags
    # IP-s
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .kubernetes.api_service_ip
      dest:
        path: .values.global.contrail_env.CONTROLLER_NODES
data:
  chart_name: analytics
  release: contrail-analytics
  namespace: tf
  wait:
    timeout: 1800
    labels:
      release_group: airship-tungstenfabric-analytics
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    global:
      contrail_env:
        LOG_LEVEL: SYS_DEBUG
        CLOUD_ORCHESTRATOR: openstack
    labels:
      analytics:
        node_selector_key: tungstenfabric-controller
        node_selector_value: enabled
  dependencies:
    - tungstenfabric-analytics-helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: tungstenfabric-analytics-helm-toolkit
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.tungstenfabric.tf-htk
      dest:
        path: .source
data:
  chart_name: tungstenfabric-analytics-helm-toolkit
  release: tungstenfabric-analytics-helm-toolkit
  namespace: helm-toolkit
  values: {}
  dependencies: []
