---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: analytics
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.tungstenfabric.analytics
      dest:
        path: .source
    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.tungstenfabric.analytics
      dest:
        path: .values.images.tags
data:
  chart_name: analytics
  release: contrail-analytics
  namespace: tf
  wait:
    timeout: 1800
    labels:
      release_group: airship-tungstenfabric-analytics
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    volume:
      enabled: false
    labels:
      server:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      prometheus_mysql_exporter:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
  dependencies: []
