---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: controller
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.tungstenfabric.controller
      dest:
        path: .source
    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.tungstenfabric.controller
      dest:
        path: .values.global.images.tags
    # IP-s
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .tungstenfabric.ip
      dest:
        path: .values.global.contrail_env.CONTROLLER_NODES
data:
  chart_name: controller
  release: contrail-controller
  namespace: tf
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    global:
      contrail_env:
        LOG_LEVEL: SYS_DEBUG
        BGP_PORT: "1179"
        CLOUD_ORCHESTRATOR: "none"
        AAA_MODE: "no-auth"
        AUTH_MODE: "noauth"
    labels:
      control:
        node_selector_key: tungstenfabric-controller
        node_selector_value: enabled
      config:
        node_selector_key: tungstenfabric-controller
        node_selector_value: enabled
      webui:
        node_selector_key: tungstenfabric-controller
        node_selector_value: enabled
      kubemanager:
        node_selector_key: tungstenfabric-controller
        node_selector_value: enabled
    manifests:
      configmap_controller_keystone: false
      daemonset_kubemanager: true
  dependencies:
    - tungstenfabric-controller-helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: tungstenfabric-controller-helm-toolkit
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.tungstenfabric.tf-htk
      dest:
        path: .source
data:
  chart_name: tungstenfabric-controller-helm-toolkit
  release: tungstenfabric-controller-helm-toolkit
  namespace: helm-toolkit
  values: {}
  dependencies: []
