---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: controller
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.tungstenfabric.controller
      dest:
        path: .source
    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.tungstenfabric.controller
      dest:
        path: .values.images.tags
data:
  chart_name: controller
  release: contrail-controller
  namespace: tf
  wait:
    timeout: 1800
    labels:
      release_group: airship-tungstenfabric-controller
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    labels:
      control:
        node_selector_key: tungstenfabric-controller
        node_selector_value: enabled
      config:
        node_selector_key: tungstenfabric-controller
        node_selector_value: enabled
      webui:
        node_selector_key: tungstenfabric-controller
        node_selector_value: enabled
  dependencies:
    - tungstenfabric-controller-helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: tungstenfabric-controller-helm-toolkit
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.tungstenfabric.tf-htk
      dest:
        path: .source
data:
  chart_name: tungstenfabric-controller-helm-toolkit
  release: tungstenfabric-controller-helm-toolkit
  namespace: helm-toolkit
  values: {}
  dependencies: []
