---
schema: promenade/Kubelet/v1
metadata:
  schema: metadata/Document/v1
  name: kubelet
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.kubernetes.pause
      dest:
        path: .images.pause
    - src:
        schema: pegleg/SeccompProfile/v1
        name: seccomp-default
        path: .seccompDirPath
      dest:
        path: .arguments[7]
        pattern: SECCOMP_PROFILE_ROOT
data:
  arguments:
    - --cni-bin-dir=/opt/cni/bin
    - --cni-conf-dir=/etc/cni/net.d
    - --eviction-max-pod-grace-period=-1
    - --network-plugin=cni
    - --node-status-update-frequency=5s
    - --serialize-image-pulls=false
    - --v=5
    - --seccomp-profile-root=SECCOMP_PROFILE_ROOT
