---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: vrouter
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.tungstenfabric.vrouter
      dest:
        path: .source
    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.tungstenfabric.vrouter
      dest:
        path: .values.global.images.tags
    # IP-s
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .tungstenfabric.ip
      dest:
        path: .values.global.contrail_env.CONTROLLER_NODES
data:
  chart_name: vrouter
  release: contrail-vrouter
  namespace: tf
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    global:
      contrail_env:
        LOG_LEVEL: SYS_DEBUG
        CLOUD_ORCHESTRATOR: openstack
        VROUTER_GATEWAY: 10.$((NET_BASE_PREFIX+1)).$JOB_RND.1
        VROUTER_ENCRYPTION: FALSE
    labels:
      vrouter_agent_kernel:
        node_selector_key: tungstenfabric-controller
        node_selector_value: enabled
    manifests:
      job_cni_init: true
  dependencies:
    - tungstenfabric-vrouter-helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: tungstenfabric-vrouter-helm-toolkit
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.tungstenfabric.tf-htk
      dest:
        path: .source
data:
  chart_name: tungstenfabric-vrouter-helm-toolkit
  release: tungstenfabric-vrouter-helm-toolkit
  namespace: helm-toolkit
  values: {}
  dependencies: []
