---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ingress-kube-system
  replacement: true
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
        name: ingress-kube-system
    actions:
        - method: merge
          path: .
  storagePolicy: cleartext
data:
  values:
    network:
      ingress:
        disable-ipv6: "true"
      vip:
        manage: true
        addr: '172.24.1.6/32'
...
